### ISSUE TITLE
Pjax 支持

### ISSUE THREAD

**Issue by oCoke** [oCoke/hexo-theme-miracle#11]
#### Issue 类型

- [ ] Bug
- [x] 新功能
- [ ] 优化
- [ ] 其他求助

**Comment by oCoke** [comment]
短期内不会支持。

**Comment by oCoke** [comment]
虽然 Pjax 会优化网页在加载时的体验，但在 Hexo 上并不能很好的适用。

Hexo 无法提供最小化数据传输的接口，直接使用只会适得其反。

**Comment by ocoke** [comment]
随着一种新的思路，我们正在重启这项 Issue。

**Comment by ocoke** [comment]
Pjax 已在 [YFun's Blog](https://blog.yfun.top/) 上支持，预计下个版本引入。

**Comment by ocoke** [comment]
经过反复考虑 我们认为这与每个博客自身设置有紧密联系。
如果你想添加 Pjax 至你的 Blog，可以参见：[什么年代还在用传统 Pjax? —— 自定义 Pjax 提升页面加载速度](https://blog.yfun.top/posts/2022/pjax/) 这篇文章，它提供了一些思路和代码。

这个 Issue 将被重新 Close。
